// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachTemplate(arg1, arg2) {
  return window['go']['bridge']['App']['AttachTemplate'](arg1, arg2);
}

export function AutoRemove() {
  return window['go']['bridge']['App']['AutoRemove']();
}

export function Bootstrap() {
  return window['go']['bridge']['App']['Bootstrap']();
}

export function Cancel(arg1) {
  return window['go']['bridge']['App']['Cancel'](arg1);
}

export function DetachTemplate(arg1) {
  return window['go']['bridge']['App']['DetachTemplate'](arg1);
}

export function GetDefault() {
  return window['go']['bridge']['App']['GetDefault']();
}

export function GetDoctor(arg1) {
  return window['go']['bridge']['App']['GetDoctor'](arg1);
}

export function GetGUISettings() {
  return window['go']['bridge']['App']['GetGUISettings']();
}

export function GetInstanceDetails(arg1) {
  return window['go']['bridge']['App']['GetInstanceDetails'](arg1);
}

export function InstallEntry(arg1) {
  return window['go']['bridge']['App']['InstallEntry'](arg1);
}

export function InstallSuggestion(arg1) {
  return window['go']['bridge']['App']['InstallSuggestion'](arg1);
}

export function Launch(arg1) {
  return window['go']['bridge']['App']['Launch'](arg1);
}

export function ListAssets() {
  return window['go']['bridge']['App']['ListAssets']();
}

export function ListAvailableSDKs() {
  return window['go']['bridge']['App']['ListAvailableSDKs']();
}

export function ListAvailableVersions(arg1) {
  return window['go']['bridge']['App']['ListAvailableVersions'](arg1);
}

export function ListInstances() {
  return window['go']['bridge']['App']['ListInstances']();
}

export function ListSources() {
  return window['go']['bridge']['App']['ListSources']();
}

export function PickIconFile() {
  return window['go']['bridge']['App']['PickIconFile']();
}

export function PickProjectDirectory() {
  return window['go']['bridge']['App']['PickProjectDirectory']();
}

export function RemoveInstance(arg1) {
  return window['go']['bridge']['App']['RemoveInstance'](arg1);
}

export function SetDefault(arg1) {
  return window['go']['bridge']['App']['SetDefault'](arg1);
}

export function SetDefaultSource(arg1) {
  return window['go']['bridge']['App']['SetDefaultSource'](arg1);
}

export function SetEnvVar(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetEnvVar'](arg1, arg2, arg3);
}

export function SetGUISettings(arg1) {
  return window['go']['bridge']['App']['SetGUISettings'](arg1);
}

export function SetInstanceIcon(arg1, arg2) {
  return window['go']['bridge']['App']['SetInstanceIcon'](arg1, arg2);
}

export function SetSourceDisabled(arg1, arg2) {
  return window['go']['bridge']['App']['SetSourceDisabled'](arg1, arg2);
}

export function Suggest(arg1) {
  return window['go']['bridge']['App']['Suggest'](arg1);
}

export function UnsetEnvVar(arg1, arg2) {
  return window['go']['bridge']['App']['UnsetEnvVar'](arg1, arg2);
}
