// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {gdit} from '../models';

export function AttachTemplate(arg1:string,arg2:string):Promise<bridge.OperationStart>;

export function AutoRemove():Promise<bridge.OperationStart>;

export function Bootstrap():Promise<bridge.AppSnapshot>;

export function Cancel(arg1:string):Promise<boolean>;

export function DetachTemplate(arg1:string):Promise<bridge.OperationStart>;

export function ForceStopSession(arg1:string):Promise<gdit.SessionInfo>;

export function GetDefault():Promise<gdit.InstanceInfo>;

export function GetDoctor(arg1:boolean):Promise<bridge.OperationStart>;

export function GetEnvironment(arg1:string):Promise<bridge.EnvironmentDetails>;

export function GetGUISettings():Promise<gdit.GUISettings>;

export function GetInstanceDetails(arg1:string):Promise<bridge.InstanceDetails>;

export function GetRoot():Promise<string>;

export function InstallEntry(arg1:gdit.InstallEntryRequest):Promise<bridge.OperationStart>;

export function InstallSuggestion(arg1:gdit.InstallSuggestionRequest):Promise<bridge.OperationStart>;

export function Launch(arg1:string):Promise<void>;

export function LaunchSession(arg1:string):Promise<gdit.SessionInfo>;

export function ListAssets():Promise<bridge.AssetSnapshot>;

export function ListAvailableSDKs():Promise<Array<gdit.SDKChannel>>;

export function ListAvailableVersions(arg1:string):Promise<Array<gdit.EngineChannel>>;

export function ListInstances():Promise<Array<gdit.InstanceInfo>>;

export function ListSessions():Promise<bridge.SessionSnapshot>;

export function ListSources():Promise<Array<gdit.SourceInfo>>;

export function PickIconFile():Promise<string>;

export function PickProjectDirectory():Promise<string>;

export function RemoveInstance(arg1:string):Promise<bridge.OperationStart>;

export function RequestStopSession(arg1:string):Promise<gdit.SessionInfo>;

export function SetDefault(arg1:string):Promise<void>;

export function SetDefaultSource(arg1:string):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetGUISettings(arg1:gdit.GUISettings):Promise<void>;

export function SetInstanceIcon(arg1:string,arg2:gdit.SetInstanceIconRequest):Promise<bridge.OperationStart>;

export function SetSourceDisabled(arg1:string,arg2:boolean):Promise<void>;

export function Suggest(arg1:string):Promise<bridge.OperationStart>;

export function UnsetEnvVar(arg1:string,arg2:string):Promise<void>;
